stages:
  download_data:
    cmd: python src/download_data.py
    outs:
      - data/raw/iris.csv

  clean_data:
    cmd: python src/clean_data.py
    deps:
      - data/raw/iris.csv
    outs:
      - data/processed/iris_processed.csv
